### ISSUE TITLE
Typo? dst_addr instead of src_addr

### ISSUE THREAD

**Issue by sir-ragna** [CarveSystems/gostringsr2#1]
This looks like a typo to me `dst_addr >= code_section["vaddr"]`, I suspect you meant `src_addr >= code_section["vaddr"]`
https://github.com/CarveSystems/gostringsr2/blob/84d5adc7a74075185c327f170e4642c77eeb7cc0/gostringsr2/gostringsr2.py#L222

Can you also share which version of radare2 you are using? I'm using `3.7.0.0` with Python `3.7.4` and `r2.cmd("pr")` returns ASCII strings instead of byte strings. I kind of suspect that this is a regression in radare2 or r2pipe.

Thanks for sharing this!

**Comment by ghost** [comment]
Yes, that is an error; it should be src_addr instead of dst_addr.

In terms of versioning, I just tested with radare2 from git (3.7.1), Python 3.7.3, r2pipe 1.4.1.

It wasn't pointed out in the blog post (for sake of clarity), but within this repo, r2pipe was extended into r2piper, strictly for the purpose of getting open._cmd_process() to return raw bytes.

Looking at the commit history of radare2/radare2-r2pipe, it looks like there has been some activity with whether bytes or a string is returned from `open_sync.open._cmd_process`. At the time gostringsr2 was written, a utf8-encoded string was returned. Looks like it's bounced between bytes and utf8 strings again.

**Comment by sir-ragna** [comment]
Thanks for the reply. I think I'll go with `r2.cmd('p8')` and `binascii.unhexlify`.

**Comment by ghost** [comment]
I incorporated your suggestion to use r2.cmd('p8') and fixed the typo in v1.1.0.

I still use a "custom" r2pipe to kill r2's stderr when it does its references search, except I call it quietr2pipe instead of r2piper.

**Comment by ghost** [comment]
Fixed in v1.1.0
